### ISSUE TITLE
Aligning transcriptions with omitted words / word placeholders

### ISSUE THREAD

**Issue by sbibauw** [synalp/jtrans#41]
The audio files I am aligning tend to have some background voices and some segments where the words have not been transcribed (e.g., because the interviewee talks to himself or to someone outside the interview context, often in another language). There are also a number of disfluencies (repetitions, false starts...) that I would like to potentially remove from the aligned transcription.

What I have observed in the alignment produced by JTrans is that, if some audible voice segments are not present in the transcription, JTrans tends to misalign everything, by assuming that the first phones it hears do correspond to the next word in the transcription, even though it does not match phonologically. For instance:

    audio:      what? ah le la- no sorry le lapin est parti
    transcript:          le                 lapin est parti
    alignment:  le    la        pin               est parti

Are there solutions to improve the accuracy of the alignment in these cases? I am thinking about:

- **Placeholders** to tell JTrans that there is some word/syllable there but it has not been transcribed (is there a conventional placeholder notation?)
- **Parameters** to tell JTrans that some words have not been transcribed and matching should be done by best phonological match? (we are talking about very short, <30sec audio files)
- Alternatively, some **word-level annotation**  that would remain in the JTR/JSON output as replacement for `type=WORD` that would allow to use the full transcript for alignment (input for JTrans in the example would be something like `[what?] [ah] le [la] [no] [sorry] [le] lapin est parti`) but then remove all `type=OTHER` (or whatever) when parsing the JSON output? (I have seen the notations for events and comments, but those are not analyzed phonologically for alignment.)

Thanks in advance!

**Comment by cerisara** [comment]
It's a good point; in theory, JTrans should be already able to handle this transparently, because there is, before *every* word to align, an optional "loop" with background phonetic models that may capture such "extra" speech. But in practice, I agree this loop fails most of the time to correctly play this role, and JTrans prefers to align these sounds with the given transcription. It's also related to the question of finding the best compromise between the background noise model and the transcription. There are potentially a lot of improvements there.

Amongst your 3 solutions, the 3rd is the best, because it's the most precise. But it requires someone to write down by hand every/most additional speech that was not in the transcription. There is no dedicated notation for that in JTrans, but it's still doable with some programming tricks, by putting before and after every not-to-transcribe speech a special comment, or a special "punctuation mark", for instance:

{bntt} what ? ah {entt} le {bntt} la no sorry le {entt} lapin est parti

Then, the output of JTrans may be filtered by some script to remove these words. This requires a bit of scripting, and may be a special re-annotation tool, but it's doable without modifying JTrans. Of course, it's also possible to introduce a new notation in JTrans - although they are already many. But I think the main issue is that it requires to manually annotate by hand all of these extra speech ! This is very often not possible I think.

The first option, placeholders, is the same idea but in a less precise way: adding just one symbol. It may indeed be used, but without information about the duration of this extra speech, it'll probably not be enough by itself.

The second option boils down proposing some kind of "tuning parameter" for the user to adjust the probability to add extra speech between words. But if we go this direction of "user feedback/correction/post-processing", then it may be simpler and faster to let the user rather correct the alignment, e.g., by clicking on the misaligned word "le", and pressing the right arrow key to force JTrans to realign with a constraint that this word appears too early. But this is a lot of programming work, and other software may be better for such manual force-alignment, like Transcriber or Praat, and we may rather think about integrating both JTrans and Transcriber may be ?

It's hard to know what's the best way to go actually :-)

**Comment by sbibauw** [comment]
Thank you for your very extensive answer!
Good to know that placeholders would probably not change much.
And great solution to use punctuation marks as delimiters for annotation! I did not think about that. Thanks a lot!
